Repository GDSC-SWU/2024-Plantry-SolutionChallenge, pull requests merged in 2024-02, with the labels that each got.

#9 [PLTR-83] 알림, 마이페이지 API 구현
  server/plantry/.gitignore
  server/plantry/build.gradle
  server/plantry/src/main/java/com/gdscplantry/plantry/PlantryApplication.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/controller/MyPageController.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/domain/Terms.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/domain/TermsRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/dto/NotificationTimeResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/dto/TermsResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/dto/UpdateNicknameResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/dto/UserProfileResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/error/MyPageErrorCode.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/service/MyPageService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/vo/TermsItemVo.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/controller/NotificationController.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/domain/Notification.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/domain/NotificationRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/dto/CheckNotificationResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/dto/NotificationItemResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/dto/NotificationListResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/dto/ProductNotificationListResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/dto/UpdateProductNotificationReqDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/error/NotificationErrorCode.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/service/NotificationService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/service/RelatedNotificationService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/service/ScheduledNotificationService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/vo/ExpNotificationProductVo.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/vo/MessageVo.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/domain/Pantry.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/domain/PantryRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/domain/ProductRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/domain/UserPantry.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/dto/product/ProductListItemResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/service/PantryService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/service/ProductService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/vo/FoodDataVo.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/User/domain/User.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/User/service/UserService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/model/NotificationTypeEnum.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/common/filter/JwtAuthorizationFilter.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/config/FcmConfig.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/error/GlobalErrorCode.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/error/handler/GlobalExceptionHandler.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/util/FcmUtil.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/util/JwtUtil.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/util/NotificationUtil.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/util/RandomUtil.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/MyPage/controller/MyPageControllerTest.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/Notification/controller/NotificationControllerTest.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/Notification/domain/NotificationRepositoryTest.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/Notification/service/RelatedNotificationServiceTest.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/Pantry/controller/PantryControllerTest.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/Pantry/controller/ProductControllerTest.java
Labels: bug, test, feature, refactoring, dependencies

#18 [PLTR-94] API 유지보수
  .gitignore
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/controller/MyPageController.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/dto/NotificationPermissionResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/MyPage/service/MyPageService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/controller/NotificationController.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/domain/Notification.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/domain/NotificationRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Notification/service/RelatedNotificationService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/controller/PantryShareController.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/domain/ProductRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/domain/UserPantryRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/dto/product/ProductListItemDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/dto/product/ProductListResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/dto/product/ProductListResultDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/dto/share/MemberDeleteResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/error/PantryErrorCode.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/service/PantryShareService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/Pantry/service/ProductService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/TrackerAndMission/controller/TrackerAndMissionController.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/TrackerAndMission/domain/mission/AchievedMissionRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/TrackerAndMission/domain/mission/MissionRepository.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/TrackerAndMission/dto/TrackerResDto.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/TrackerAndMission/service/TrackerService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/User/domain/User.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/User/service/UserService.java
  server/plantry/src/main/java/com/gdscplantry/plantry/domain/model/StorageEnum.java
  server/plantry/src/main/java/com/gdscplantry/plantry/global/common/filter/JwtAuthorizationFilter.java
  server/plantry/src/test/java/com/gdscplantry/plantry/domain/Pantry/controller/ProductControllerTest.java
Labels: bug, deployment, feature, refactoring

#19 [PLTR-102] AI/ML 수정사항 반영
  aiml/main.py
Labels: bug

#22 [PLTR-99] QA 에러 수정(alarm, signin, profile, ocr)
  Android/app/src/main/java/com/plantry/presentation/addfood/popup/ocr/MultiAddFoodPopUp.kt
  Android/app/src/main/java/com/plantry/presentation/addfood/viewmodel/ocr/OcrSubmitViewModel.kt
  Android/app/src/main/java/com/plantry/presentation/auth/ui/SignInActivity.kt
  Android/app/src/main/java/com/plantry/presentation/auth/viewmodel/SignInViewModel.kt
  Android/app/src/main/java/com/plantry/presentation/home/viewholder/notification/HomeNotificationViewHolder.kt
  Android/app/src/main/java/com/plantry/presentation/profile/ui/FragmentProfileEdit.kt
  Android/app/src/main/java/com/plantry/presentation/profile/viewmodel/ProfileNameChangeViewModel.kt
Labels: bug

#25 Resolve/develop -> Main
  Android/app/src/main/java/com/plantry/presentation/addfood/popup/ocr/MultiAddFoodPopUp.kt
  Android/app/src/main/java/com/plantry/presentation/addfood/viewmodel/ocr/OcrSubmitViewModel.kt
  Android/app/src/main/java/com/plantry/presentation/auth/ui/SignInActivity.kt
  Android/app/src/main/java/com/plantry/presentation/auth/viewmodel/SignInViewModel.kt
  Android/app/src/main/java/com/plantry/presentation/home/viewholder/notification/HomeNotificationViewHolder.kt
  Android/app/src/main/java/com/plantry/presentation/profile/ui/FragmentProfileEdit.kt
  Android/app/src/main/java/com/plantry/presentation/profile/viewmodel/ProfileNameChangeViewModel.kt
Labels: bug, feature, refactoring

#28 Resolve/develop -> Main
  Android/.gitignore
  Android/.idea/deploymentTargetDropDown.xml
  Android/app/src/main/java/com/plantry/presentation/auth/ui/SignInActivity.kt
  Android/app/src/main/res/values/strings.xml
Labels: bug

#29 docs: update gitnore
  README.md
Labels: documentation
